version: "3.9"

services:
  db:
    image: postgres:16
    container_name: finance-pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finance_data
    ports:
      - "5432:5432"
    volumes:
      - finance_pg_data:/var/lib/postgresql/data

volumes:
  finance_pg_data:
